Closes #45: Add CORS Implementation for Outbox-Rest
kadai-io/KadaiAdapter pull request #46
Opened 2024-12-05 11:57 UTC by jamesrdi

### Thanks for your PR! Please fill out the following list :)

---

- [ ] I put the ticket or multiple tickets in review
- [ ] Commit message format → Closes #&lt;Issue Number&gt; - Your commit message.
- [ ] Sonarcloud link : \<add the link here>
- [ ] No documentation update needed
- [ ] Link to PR with documentation update: \<add the link here>
- [ ] No Release Notes needed
- [ ] Release Notes :

```

```

2025-01-24 06:57 UTC, CRoberto1926 commented on kadai-adapter-camunda-outbox-rest/pom.xml
> +        <java.version>17</java.version>
Is it ok to update to Java 17 in this PR?

2025-01-24 06:57 UTC, CRoberto1926 commented on kadai-adapter-camunda-outbox-rest/src/main/java/io/kadai/adapter/camunda/outbox/rest/controller/CamundaTaskEventsController.java
> +  public Response getCsrfToken() {
Why do you need a specific endpoint for CSRF? The Header or Cookie should be included in every existing request, without the need for a specific endpoint, as far as I know.

2025-01-24 06:57 UTC, CRoberto1926 commented on kadai-adapter-camunda-outbox-rest/src/main/java/io/kadai/adapter/camunda/outbox/rest/filter/CsrfTokenIssuanceFilter.java
> +    if (requestContext.getCookies().containsKey(CSRF_TOKEN_COOKIE_NAME)) {
Shouldn't you also check the value of the cookie, and not only its key?

2025-01-24 06:57 UTC, CRoberto1926 commented on kadai-adapter-camunda-outbox-rest/src/main/java/io/kadai/adapter/camunda/outbox/rest/filter/CsrfTokenService.java
> +  public boolean validateToken(String encodedTokenAndSignature) {
I'm not 100% sure how this works, could you explain it to me?

2025-01-24 06:57 UTC, CRoberto1926 commented on kadai-adapter-camunda-outbox-rest/src/main/java/io/kadai/adapter/camunda/outbox/rest/filter/CsrfValidationFilter.java
> +  private static final String CSRF_TOKEN_HEADER_NAME = "X-XSRF-TOKEN";
Could you be consisten between CSRF and XSRF? Please choose one and use it everywhere (this comment is valid for the entire PR)

2025-01-24 06:57 UTC, CRoberto1926 commented on kadai-adapter-camunda-outbox-rest/src/main/java/io/kadai/adapter/camunda/outbox/rest/filter/CsrfValidationFilter.java
> +  private static final String CSRF_TOKEN_ISSUE_ENDPOINT = "/events/csrf";
Why a specific endpoint? Shouldn't all requests be checked?

2025-01-24 06:57 UTC, CRoberto1926 commented on kadai-adapter-camunda-system-connector/src/main/java/io/kadai/adapter/systemconnector/camunda/api/impl/HttpHeaderProvider.java
> +      headers.add("X-XSRF-TOKEN", csrfToken);          // Add token to custom header
Isn't this one enough? Why 2 headers?

2025-01-24 06:57 UTC, CRoberto1926 commented on kadai-adapter/src/main/java/io/kadai/adapter/impl/CsrfTokenRetriever.java
> +        this.csrfTokenReceived = true;
I don't understand this: are you retrieving the CSRF Token only once at startup? And why is `systemConnector.retrieveCsrfToken()` returning void? Shouldn't it return a boolean or the token itself?

2025-01-24 06:57 UTC, CRoberto1926 commented on kadai-adapter/src/main/java/io/kadai/adapter/monitoring/OutboxHealthCheck.java
> +    replaceCookieStore(restTemplate);
With an HealthCheck ping you are replacing all cookies? Did I understand this correctly?

2025-01-24 08:42 UTC, jamesrdi commented on kadai-adapter-camunda-outbox-rest/pom.xml
> +        <java.version>17</java.version>
You're right, I accidentally changed it. I will change it back

2025-03-07 06:19 UTC, CRoberto1926 commented on kadai-adapter-camunda-spring-boot-test/src/test/java/io/kadai/adapter/integration/CamundaTaskEventErrorHandlerTest.java
> +                          Thread.sleep(1000);
Can we avoid Thread.sleep?

2025-03-07 06:19 UTC, CRoberto1926 commented on kadai-adapter-camunda-spring-boot-test/src/test/java/io/kadai/adapter/integration/HttpHeaderProviderWithCsrfToken.java
> +    assertThat(headers).containsKeys("Authorization", "Cookie", "X-XSRF-TOKEN");
Maybe also check the value of Cookie and X-XSRF-TOKEN?

2025-03-07 06:19 UTC, CRoberto1926 commented on kadai-adapter-camunda-system-connector/src/main/java/io/kadai/adapter/systemconnector/camunda/api/impl/HttpHeaderProvider.java
> +  @Value("${kadai.adapter.xsrf.token:}")
Do we want to add this in application.property as empty? Or even commented?

2025-03-07 08:54 UTC, jamesrdi commented on kadai-adapter-camunda-spring-boot-test/src/test/java/io/kadai/adapter/integration/CamundaTaskEventErrorHandlerTest.java
> +                          Thread.sleep(1000);
This was a test to resolve the error on the pipeline

2025-03-07 08:56 UTC, jamesrdi commented on kadai-adapter-camunda-system-connector/src/main/java/io/kadai/adapter/systemconnector/camunda/api/impl/HttpHeaderProvider.java
> +  @Value("${kadai.adapter.xsrf.token:}")
Do you mean in the property for the KadaiAdapterApplication or the property for the KadaiAdapterTestApplication. Maybe I can comment them

2025-03-07 08:56 UTC, jamesrdi commented on kadai-adapter-camunda-spring-boot-test/src/test/java/io/kadai/adapter/integration/HttpHeaderProviderWithCsrfToken.java
> +    assertThat(headers).containsKeys("Authorization", "Cookie", "X-XSRF-TOKEN");
Yes that's a good idea

2025-03-07 10:06 UTC, CRoberto1926 approved these changes
LGTM

2025-03-07 10:27 UTC, gitgoodjhe requested changes

2025-03-07 10:27 UTC, gitgoodjhe commented on kadai-adapter-camunda-spring-boot-test/src/test/java/io/kadai/adapter/integration/HttpHeaderProviderWithCsrfToken.java
> +class HttpHeaderProviderWithCsrfToken {
Test class usually always have TestXXX oder XXXTest in the name...did we just miss this here or is there a specific reason?

2025-03-07 11:04 UTC, CRoberto1926 commented on kadai-adapter-camunda-spring-boot-test/src/test/java/io/kadai/adapter/integration/HttpHeaderProviderWithCsrfToken.java
> +class HttpHeaderProviderWithCsrfToken {
Sorry, I missed it... My bad

2025-03-10 13:55 UTC, jamesrdi commented on kadai-adapter-camunda-spring-boot-test/src/test/java/io/kadai/adapter/integration/HttpHeaderProviderWithCsrfToken.java
> +class HttpHeaderProviderWithCsrfToken {
You're right I have changed it

2025-03-14 12:42 UTC, gitgoodjhe approved these changes

2025-03-14 12:45 UTC, merged